document:
  name: Linee Guida SPID - Rilascio dell'identità digitale per uso professionale
  description:
      SPID - Rilascio dell'identità digitale per uso professionale
  tags:
    - spid
    - identità digitale
    - persone giuridiche
    - legal person
    - uso professionale
